services:
  wordpress:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    env_file: 
      - .env
    depends_on:
      - mysql
    volumes:
      - wordpress_data:/var/www/html
      - ./bdm-digital-payment-gateway:/var/www/html/wp-content/plugins/bdm-digital-payment-gateway

  mysql:
    image: mariadb:latest
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "3307:3306"
    env_file:
      - .env

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - mysql
    ports:
      - "8082:80"
    environment:
      PMA_HOST: ${WORDPRESS_DB_HOST}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    env_file:
      - .env
volumes:
  wordpress_data: